#! /bin/bash

# =======================================================================
# ===== CHECK FOR ARG ===================================================
# =======================================================================
if [ $# -eq 0 ]; then
  echo "No filename provided -- operation aborted" 
  exit 1
fi

# =======================================================================
# ===== CHECK IF FILE IN BIN ============================================
# =======================================================================
if [ ! -f /$HOME/recyclebin/$1 ] ; then
  echo "File does not exist –- operation aborted" 
  exit 1
fi

# =======================================================================
# ===== CHECK IF FILE WILL BE OVERWRITTEN ===============================
# =======================================================================
if [ -f ./$(echo $1 | cut -d"_" -f1) ]; then    
    read -p "File with similar name exists -- do you want to overwrite? y/n" input
    # prompt for input to overwrite file
    if [[ ! $input =~ ^[Yy] ]]; then      
      echo "Action cancelled -- operation aborted" 
      exit 1
    fi
fi

# ===== GET ORIGINAL NAME ===============================================
originalName=$(grep $1 /$HOME/.restore.info | cut -d":" -f1 | cut -d"_" -f1)
# ===== GET ABSOLUTE PATH  ==============================================
path=$(grep $1 /$HOME/.restore.info | cut -d":" -f2)
# ===== CREATE MISSING DIR ==============================================
mkdir -p $path
# ===== MOVE AND RENAME  ================================================
mv $HOME/recyclebin/$1 $path$originalName
# ===== REMOVE LOG ENTRY ================================================
sed -i "/$1/d" /$HOME/.restore.info
# ===== OUTPUT SUCCESS ==================================================
echo "Success! -- $originalName restored"
# ===== EXIT ============================================================
exit 0
